name: Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 * * *"
  push:
    branches: [main]

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS : False
          SHOW_COMMIT : False
          SHOW_DAYS_OF_WEEK : False
          SHOW_LANGUAGE : True
          SHOW_OS : True
          SHOW_PROJECTS : False
          SHOW_TIMEZONE : False
          SHOW_EDITORS : True
          SHOW_LANGUAGE_PER_REPO : False
          SHOW_LOC_CHART : False
          SHOW_SHORT_INFO : False
